# Generated by Django 3.1.7 on 2021-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='elo',
            new_name='blitz_elo',
        ),
        migrations.AddField(
            model_name='player',
            name='bullet_elo',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='player',
            name='classical_elo',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='player',
            name='rapid_elo',
            field=models.IntegerField(default=1200),
        ),
    ]
