# Generated by Django 3.1.7 on 2021-05-20 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210520_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
